### ISSUE TITLE
Keyboard not registering

### ISSUE THREAD

**Issue by MintStudios** [andresavic/AmongKey#1] opened 2020-11-30 16:19 UTC
This seems to be the main issue with this program at the moment, I'll put it here.
The ML model successfully predicts the state of the game, but does not simulate movement at all. Accessibility and input monitoring are turned on.

**Comment by MintStudios** [comment] 2020-11-30 16:25
Cloning AmongKey and trying to build it reveals an error in Xcode.
Cannot find 'AmongUsClassifier' in scope
This problem is in AmongKeyApp.swift and on line 146.

**Comment by andresavic** [comment] 2020-11-30 16:31
> Cloning AmongKey and trying to build it reveals an error in Xcode.
> Cannot find 'AmongUsClassifier' in scope
> This problem is in AmongKeyApp.swift and on line 146.

Fixed with Commit #7e25946

**Comment by MintStudios** [comment] 2020-11-30 16:40
I've built it myself, to see if things would change, but AmongKey is not moving among us at all.

**Comment by andresavic** [comment] 2020-11-30 16:45
@MintStudios https://github.com/andresavic/AmongKey/blob/292b227db19fbec7470e49d1840a6d336a05742f/AmongKey/Keymapping.swift#L12
Add at Line 12 in the Keymapping.swift `print(event.keyCode)`

In the console you should then see if keys are recognition in general.

**Comment by MintStudios** [comment] 2020-11-30 16:52
Yes, the keys are being recognized. In which part of the code is the character moved (the mouse, really)

**Comment by andresavic** [comment] 2020-11-30 16:58
https://github.com/andresavic/AmongKey/blob/292b227db19fbec7470e49d1840a6d336a05742f/AmongKey/AmongKeyApp.swift#L85
calculates the joystick position

mouseDown and mouseUp simulates the mouse events.

**Comment by MintStudios** [comment] 2020-11-30 17:16
@andresavic 
I've put some print functions in places, and the farthest I've gotten is inside a case in in a simulation of a key press:
```
case (49, "Ingame"), (14, "Ingame"), (49, "Lobby"), (14, "Lobby"):
            print("Use button")
            simulateClick(pos: USE_BUTTON)
            break;
```
I've gotten the print function inside the `simulateClick()` function, but I haven't further tested it. What do you thing?

**Comment by MintStudios** [comment] 2020-11-30 17:21
Aha, I think I have the problem. In `simulateClick()` the program returns.
```
func simulateClick(pos: (x: Int, y: Int)) {
    print("Simulating click")
    if (X == 0 && Y == 0) {
        print("Returning in simulating")
        return;
    }
```

**Comment by andresavic** [comment] 2020-11-30 17:25
@MintStudios Put a print or breakpoint in here
https://github.com/andresavic/AmongKey/blob/292b227db19fbec7470e49d1840a6d336a05742f/AmongKey/AmongKeyApp.swift#L211

Also remove "Accessibility" permission for AmongKey. Run the app from Xcode and there should be a new entry inside "Accessibility" and mark the checkmark. Then stop the app and run it again.

You can leave Among Us the whole time open inside the Freeplay.

**Comment by MintStudios** [comment] 2020-11-30 17:30
I already have. I think the problem is that in `simulateClick()`, it never even gets to the code. It returns in the if statement.

**Comment by andresavic** [comment] 2020-11-30 17:31
> Aha, I think I have the problem. In `simulateClick()` the program returns.
> 
> ```
> func simulateClick(pos: (x: Int, y: Int)) {
>     print("Simulating click")
>     if (X == 0 && Y == 0) {
>         print("Returning in simulating")
>         return;
>     }
> ```

It should only return when X and Y are zero because then the window position is unknown. But I don't think this is the issue because you told me that the Screen capture is working fine. X and Y are set in the amongusWindow() function.

**Comment by MintStudios** [comment] 2020-11-30 17:32
@andresavic but for some reason, it still returns there. So it must be the problem somehow.

**Comment by andresavic** [comment] 2020-11-30 17:33
> I already have. I think the problem is that in `simulateClick()`, it never even gets to the code. It returns in the if statement.

Oh. Please debug https://github.com/andresavic/AmongKey/blob/292b227db19fbec7470e49d1840a6d336a05742f/AmongKey/AmongKeyApp.swift#L117

Maybe there is the issue that X and Y is never set properly .

**Comment by MintStudios** [comment] 2020-11-30 17:34
Yep, I was just doing that now. I was printing `bounds`, and this is what I got:
```
["X": 0, "Y": 81, "Width": 788, "Height": 619]
["X": 0, "Width": 788, "Height": 619, "Y": 81]
["Width": 788, "Height": 619, "X": 0, "Y": 81]
["X": 0, "Width": 788, "Height": 619, "Y": 81]
["X": 0, "Width": 788, "Height": 619, "Y": 81]
["Width": 788, "Height": 619, "X": 0, "Y": 81]
["X": 0, "Height": 619, "Width": 788, "Y": 81]
["X": 0, "Y": 81, "Width": 788, "Height": 619]
["Width": 788, "Height": 619, "Y": 81, "X": 0]
["Width": 788, "Height": 619, "X": 0, "Y": 81]
["X": 0, "Width": 788, "Height": 619, "Y": 81]
["X": 0, "Y": 81, "Width": 788, "Height": 619]
```

**Comment by MintStudios** [comment] 2020-11-30 17:36
Printing X and Y reveals this:
```
341 44
0 0
341 44
0 0
341 44
0 0
341 44
0 0
341 44
0 0
341 44
0 0
341 44
0 0
341 44
0 0
341 44
0 0
341 44
0 0
```

**Comment by andresavic** [comment] 2020-11-30 17:57
I do my best to reproduce this issue. Even after running `tccutil reset All` and rebooting my MacBook Air and without granting any permission I can print valid X and Y values. Very confusing.

**Comment by MintStudios** [comment] 2020-11-30 21:51
with commit #8c56a4d41d7e3a608afc182308793c2c88d32eaf this issue is fixed.

**Comment by andresavic** [comment] 2020-11-30 21:54
@MintStudios Thank you very much for troubleshooting this nasty bug. Short explanation: On Macs with Touchbar the CGWindowListCopyWindowInfo contains for mobile apps a second entry with the same kCGWindowOwnerName.

**Closed by andresavic** 2020-11-30 21:54 UTC
